[package]
name = "actiondb"
version = "0.1.0"
authors = ["Tibor Benke <tibor.benke@balabit.com>"]

[[bin]]
name = "adbtool"
path = "src/bin/adbtool.rs"

[dependencies]
clap = "*"
log = "*"
uuid = "*"
yaml-rust = "0.2"
